#!/bin/sh
# chkconfig: 345 99 01
# processname: ansilounge
# description: Starts and stops ansilounge service

SERVICE_NAME=ansilounge
PATH_TO_JAR=/opt/ansilounge/bin/ansilounge.jar
PID_PATH_NAME=/var/run/ansilounge.pid
CONF_FILE=/opt/ansilounge/etc/ansilounge.conf
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -Xmx4096m -jar $PATH_TO_JAR -c $CONF_FILE /tmp 2>> /opt/ansilounge/logs/ansilounge.log >> /opt/ansilounge/logs/ansilounge.log &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
 
